name: Build

on:
  push:
    branches:
      - main

jobs:
  npm:
    name: Build tailwindcss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js lts
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b build
      - run: npm run build
      - name: Git commit
        run: |
          git add -f dist/output.css
          git commit -m "Build"
      - name: Git push
        run: |
          git push origin build --force
